### ISSUE TITLE
Readme incorrect CMake options

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU2-pedestrian_navigation-example#8]
The readme for this repository includes old CMake options such as `CUDA_ARCH`, rather than the now-used `CMAKE_CUDA_ARCHITECTURES`. 

We should fix this, and check our other standalone repos' too.

**Comment by Robadob** [comment]
Had a quick click through the repos, these seem to be the only ones with the same issue (benchmarks and template were `CMAKE_CUDA_ARCHITECTURES`).
https://github.com/FLAMEGPU/FLAMEGPU2-worked-example
https://github.com/FLAMEGPU/FLAMEGPU2-tutorial-cudacpp
